module.exports = {
  skills: [
    { name: 'Security Operations', category: 'Defensive', subs: ['SIEM (Splunk/Sentinel)', 'Log Analysis', 'Alert Triage', 'SOAR'] },
    { name: 'Incident Response', category: 'Defensive', subs: ['Containment', 'Forensics', 'Root Cause Analysis', 'Playbooks'] },
    { name: 'Threat Intelligence', category: 'Defensive', subs: ['IOC Analysis', 'MITRE ATT&CK', 'Threat Hunting'] },
    { name: 'Penetration Testing', category: 'Offensive', subs: ['Web App Testing', 'Network Testing', 'Active Directory', 'Reporting'] },
    { name: 'Cloud Security', category: 'Cloud', subs: ['AWS Security', 'Azure Security', 'Container Security', 'IaC Scanning'] },
    { name: 'Identity & Access Management', category: 'Architecture', subs: ['SSO & MFA', 'Privileged Access', 'Zero Trust'] },
    { name: 'Governance Risk & Compliance', category: 'GRC', subs: ['ISO 27001', 'Risk Assessment', 'Audit', 'Policy'] },
    { name: 'Network Security', category: 'Infrastructure', subs: ['Firewalls', 'IDS/IPS', 'VPN', 'Segmentation'] },
    { name: 'Application Security', category: 'Offensive', subs: ['SAST/DAST', 'Secure Code Review', 'OWASP Top 10'] },
  ],
  trainings: [
    { name: 'CISSP', vendor: 'ISC2', category: 'security', type: 'certification' },
    { name: 'CISM', vendor: 'ISACA', category: 'security', type: 'certification' },
    { name: 'CEH (Certified Ethical Hacker)', vendor: 'EC-Council', category: 'security', type: 'certification' },
    { name: 'OSCP', vendor: 'OffSec', category: 'security', type: 'certification' },
    { name: 'CompTIA Security+', vendor: 'CompTIA', category: 'security', type: 'certification' },
    { name: 'ISO 27001 Lead Auditor', vendor: 'BSI', category: 'grc', type: 'certification' },
    { name: 'Microsoft SC-200 (Security Operations Analyst)', vendor: 'Microsoft', category: 'cloud', type: 'certification' },
    { name: 'AWS Certified Security – Specialty', vendor: 'AWS', category: 'cloud', type: 'certification' },
    { name: 'GIAC GCIH (Incident Handler)', vendor: 'GIAC', category: 'security', type: 'certification' },
  ],
  people: [
    { name: 'Daniel Okafor', role: 'Head of Cyber' },
    { name: 'Priya Sharma', role: 'SOC Analyst' },
    { name: 'Ryan MacLeod', role: 'Penetration Tester' },
    { name: 'Hannah Lewis', role: 'Incident Responder' },
    { name: 'Mohammed Iqbal', role: 'Security Engineer' },
    { name: 'Lucy Fairweather', role: 'GRC Analyst' },
    { name: 'Callum Reid', role: 'Threat Intelligence Analyst' },
    { name: 'Aisha Khan', role: 'Cloud Security Engineer' },
    { name: 'Nathan Brooks', role: 'SOC Analyst' },
    { name: 'Freya Donnelly', role: 'Security Architect' },
    { name: 'Samuel Owusu', role: 'Penetration Tester' },
    { name: 'Chloe Ashworth', role: 'IAM Specialist' },
    { name: 'Adam Pickering', role: 'AppSec Engineer' },
  ],
};
