module.exports = {
  skills: [
    { name: 'Software Engineering', category: 'Development', subs: ['JavaScript/TypeScript', 'Python', 'Java', 'Code Review'] },
    { name: 'Cloud Platforms', category: 'Cloud', subs: ['AWS', 'Azure', 'GCP', 'Cost Optimisation'] },
    { name: 'DevOps & CI/CD', category: 'Platform', subs: ['Docker', 'Kubernetes', 'Terraform', 'Pipelines (GitHub Actions)'] },
    { name: 'Systems Design', category: 'Architecture', subs: ['Scalability', 'Resilience', 'API Design', 'Event-Driven'] },
    { name: 'Databases', category: 'Data', subs: ['PostgreSQL', 'Query Optimisation', 'Data Modelling', 'NoSQL'] },
    { name: 'Testing & QA', category: 'Quality', subs: ['Unit Testing', 'Integration Testing', 'Test Automation', 'Performance Testing'] },
    { name: 'Networking', category: 'Infrastructure', subs: ['TCP/IP', 'DNS', 'Load Balancing', 'CDN'] },
    { name: 'Observability', category: 'Platform', subs: ['Logging', 'Metrics', 'Tracing', 'Alerting'] },
    { name: 'Security Engineering', category: 'Quality', subs: ['Secure Defaults', 'Secrets Management', 'Dependency Scanning'] },
  ],
  trainings: [
    { name: 'AWS Certified Solutions Architect – Associate', vendor: 'AWS', category: 'cloud', type: 'certification' },
    { name: 'Microsoft Azure Administrator (AZ-104)', vendor: 'Microsoft', category: 'cloud', type: 'certification' },
    { name: 'Certified Kubernetes Administrator (CKA)', vendor: 'CNCF', category: 'platform', type: 'certification' },
    { name: 'HashiCorp Terraform Associate', vendor: 'HashiCorp', category: 'platform', type: 'certification' },
    { name: 'TOGAF 9 Foundation', vendor: 'The Open Group', category: 'architecture', type: 'certification' },
    { name: 'Professional Scrum Developer', vendor: 'Scrum.org', category: 'process', type: 'certification' },
    { name: 'Google Professional Cloud Architect', vendor: 'Google', category: 'cloud', type: 'certification' },
    { name: 'Chartered Engineer (CEng) Pathway', vendor: 'Engineering Council', category: 'professional', type: 'training' },
  ],
  people: [
    { name: 'James Whitfield', role: 'Engineering Lead' },
    { name: 'Sarah Donovan', role: 'Senior Software Engineer' },
    { name: 'Ben Carmichael', role: 'DevOps Engineer' },
    { name: 'Olivia Hartley', role: 'Software Engineer' },
    { name: 'Raj Malhotra', role: 'Cloud Architect' },
    { name: 'Megan Pryce', role: 'QA Engineer' },
    { name: 'Tom Ellingham', role: 'Platform Engineer' },
    { name: 'Niamh Gallagher', role: 'Software Engineer' },
    { name: 'David Sinclair', role: 'Database Engineer' },
    { name: 'Rebecca Nolan', role: 'Site Reliability Engineer' },
    { name: 'Aaron Whitcombe', role: 'Software Engineer' },
    { name: 'Lauren Beckett', role: 'Senior Software Engineer' },
    { name: 'Kieran Doyle', role: 'DevOps Engineer' },
    { name: 'Hannah Stirling', role: 'Engineering Manager' },
  ],
};
