module.exports = {
  skills: [
    { name: 'Pipeline Management', category: 'Sales Process', subs: ['Lead Qualification', 'Forecasting', 'Pipeline Hygiene', 'Deal Review'] },
    { name: 'Negotiation', category: 'Selling', subs: ['Commercial Terms', 'Objection Handling', 'Closing Techniques'] },
    { name: 'CRM', category: 'Tools', subs: ['Salesforce', 'HubSpot', 'Reporting & Dashboards'] },
    { name: 'Solution Selling', category: 'Selling', subs: ['Discovery', 'Value Proposition', 'Demos & POCs'] },
    { name: 'Account Management', category: 'Post-Sale', subs: ['Renewals', 'Upsell & Cross-sell', 'QBRs'] },
    { name: 'Bid & Tender Management', category: 'Sales Process', subs: ['RFP Response', 'Pricing Strategy', 'Proposal Writing'] },
    { name: 'Commercial Awareness', category: 'Business', subs: ['Market Analysis', 'Competitor Intel', 'Margin Management'] },
    { name: 'Prospecting', category: 'Selling', subs: ['Cold Outreach', 'Social Selling', 'Networking'] },
  ],
  trainings: [
    { name: 'Salesforce Certified Administrator', vendor: 'Salesforce', category: 'crm', type: 'certification' },
    { name: 'MEDDIC Fundamentals', vendor: 'MEDDIC Academy', category: 'methodology', type: 'course' },
    { name: 'SPIN Selling', vendor: 'Huthwaite', category: 'methodology', type: 'course' },
    { name: 'Miller Heiman Strategic Selling', vendor: 'Korn Ferry', category: 'methodology', type: 'course' },
    { name: 'APMP Foundation (Bid Management)', vendor: 'APMP', category: 'bid', type: 'certification' },
    { name: 'HubSpot Sales Software', vendor: 'HubSpot', category: 'crm', type: 'certification' },
    { name: 'Negotiation Mastery', vendor: 'Harvard Online', category: 'skills', type: 'course' },
    { name: 'Challenger Sale', vendor: 'Gartner', category: 'methodology', type: 'course' },
  ],
  people: [
    { name: 'Oliver Bennett', role: 'Sales Director' },
    { name: 'Amelia Clarke', role: 'Account Executive' },
    { name: 'Harry Thompson', role: 'Business Development Manager' },
    { name: 'Sophie Walsh', role: 'Account Executive' },
    { name: 'Jack Robinson', role: 'Sales Development Rep' },
    { name: 'Charlotte Hughes', role: 'Key Account Manager' },
    { name: 'George Patel', role: 'Solutions Consultant' },
    { name: 'Emily Carter', role: 'Account Executive' },
    { name: 'Thomas Wright', role: 'Bid Manager' },
    { name: 'Isla Murray', role: 'Sales Development Rep' },
    { name: 'William Foster', role: 'Commercial Manager' },
    { name: 'Grace Edwards', role: 'Account Executive' },
  ],
};
